name: dynamic_fonts
description: A package to include dynamic web-hosted fonts in your Flutter app.
version: 2.2.1
homepage: https://github.com/amake/dynamic-fonts-flutter/

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=2.10.0-0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  path_provider: ^2.0.0
  crypto: ^3.0.0

dev_dependencies:
  cider: ">=0.1.3 <0.3.0"
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  mustache_template: ^2.0.0
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.2
  protobuf: ">=2.0.1 <4.0.0"
  test: ^1.19.5
