# Checks that are run on every commit to main and every pull request.
name: Checks

on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  check_package:
    name: packages/${{ matrix.package }}
    runs-on: macos-latest
    strategy:
      matrix:
        package: [google_fonts]
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Install Flutter
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa # v2.10.0
        with:
          channel: beta
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'

      - name: Get packages
        run: flutter pub get

      - name: Analyze Dart code
        run: flutter analyze

      - name: Ensure Dart code is formatted correctly
        run: dart format --set-exit-if-changed .

      - name: Run Flutter unit tests
        run: flutter test
